version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"     # ou "daily" si tu veux accélérer la détection
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
